##############################################################
# PUFlib Makefile
# Description: Compiles PUFlic
#
# Author: Jacob I. Torrey
# Date: 5/17/2016
##############################################################
SHELL:=/bin/bash

# Variables used by the Makefile
CC ?= $(shell command -v colorgcc || command -v gcc)
LINKER = ld

CFLAGS = -O2 -I. -g -Wall -fPIC

MODULES = puflibtest

MODULE_DIRS = $(patsubst %,modules/%,${MODULES})
MODULE_SOURCES = $(foreach mod,${MODULE_DIRS},$(wildcard ${MODULE_DIRS}/*.c))
MODULE_OBJECTS = $(patsubst %.c,%.o,${MODULE_SOURCES})

SONAME_FULL  = libpuf.so.1.0.1
SONAME_MID   = libpuf.so.1
SONAME_SHORT = libpuf.so

# List all the objects needed here
OBJECTS = puflib.o module_list.o ${MODULE_OBJECTS}

${SONAME_FULL}: $(OBJECTS)
	$(CC) -shared -Wl,-soname,${SONAME_MID} -o ${SONAME_FULL} $(OBJECTS)
	ln -fs ${SONAME_FULL} ${SONAME_MID}
	ln -fs ${SONAME_FULL} ${SONAME_SHORT}

test: test.c ${SONAME_FULL}
	${CC} ${CFLAGS} -L. -lpuf -o test test.c

module_list.c:
	@echo Generate module_list.c...
	@( echo // WARNING: this file is autogenerated by Makefile. Do not edit! ; echo ; \
	  echo "#include <puflib.h>" ; echo ; \
	  for modname in ${MODULES}; do  \
	    echo "extern module_info const MODULE_INFO__$$modname;" ; \
	  done; echo; \
	  echo 'module_info const * const PUFLIB_MODULES[] = {' ; \
	  for modname in ${MODULES}; do  \
	  	echo "    &MODULE_INFO__$$modname," ; \
	  done ; \
	  echo "    (module_info const *) 0,"; \
	  echo }\; ; \
	  ) > module_list.c

clean:
	-rm ${SONAME_FULL} ${SONAME_MID} ${SONAME_SHORT}
	-rm test
	-rm ${OBJECTS}
	-rm module_list.c
